spring.application.name=FIle.Manager
spring.datasource.url=jdbc:h2:file:./data/bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=localhost
spring.datasource.password=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080